name = "parahub"
compatibility_date = "2026-05-22"
main = "src/worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "parahub-db"
database_id = "34f087d5-48d2-4c98-ba73-d861461ed0c1"
